(()=>{
const cabinet=document.querySelector('.cabinet-inner');
if(!cabinet)return;
const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('bridge-layer');cabinet.appendChild(svg);
let bridgeMode=false,start=null,bridges=[],seq=1;
const consoleBox=document.querySelector('.wiring-console');
if(consoleBox){const btn=document.createElement('button');btn.id='bridgeModeBtn';btn.className='bridge-mode-btn';btn.textContent='⛓ MOSTEK / GRZEBIEŃ ZASILAJĄCY';consoleBox.appendChild(btn);const help=document.createElement('div');help.className='bridge-help';help.innerHTML='Mostki służą do krótkiego połączenia górnych zacisków fazowych sąsiednich zabezpieczeń B10/B16/RCBO. Najpierw zasil pierwszy aparat przewodem, potem wykonaj mostki dalej.';consoleBox.appendChild(help);btn.onclick=()=>toggleMode(!bridgeMode)}
function mountedOf(t){return t.closest('.mounted-device')}
function codeOf(t){return mountedOf(t)?.dataset.code||''}
function eligible(t){if(!t?.classList.contains('wire-terminal'))return false;if(t.dataset.zone!=='top')return false;const code=codeOf(t);if(!['B10','B16','RCBO'].includes(code))return false;return ['L','L1','L2','L3'].includes(t.dataset.role)}
function toggleMode(on){bridgeMode=on;const btn=document.getElementById('bridgeModeBtn');if(btn)btn.classList.toggle('active',on);clearStart();document.querySelectorAll('.wire-terminal').forEach(t=>t.classList.toggle('bridge-eligible',on&&eligible(t)));const status=document.getElementById('wiringStatus');if(status)status.innerHTML=on?'<b>MOSTEK:</b> kliknij górny zacisk L pierwszego zabezpieczenia, a potem górny zacisk L następnego.':'<b>PRZEWODY:</b> wybierz żyłę i wykonuj zwykłe połączenia.'}
function clearStart(){if(start?.el)start.el.classList.remove('bridge-start');start=null}
function center(el){const r=el.getBoundingClientRect(),c=cabinet.getBoundingClientRect();return{x:r.left+r.width/2-c.left,y:r.top+r.height/2-c.top}}
function addPath(d,phase,cls){const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);p.setAttribute('class',cls);p.dataset.phase=phase;svg.appendChild(p)}
function redraw(){svg.innerHTML='';bridges=bridges.filter(b=>document.querySelector(`[data-terminal="${CSS.escape(b.a)}"]`)&&document.querySelector(`[data-terminal="${CSS.escape(b.b)}"]`));bridges.forEach((b,i)=>{const a=document.querySelector(`[data-terminal="${CSS.escape(b.a)}"]`),z=document.querySelector(`[data-terminal="${CSS.escape(b.b)}"]`);if(!a||!z)return;const A=center(a),B=center(z),y=Math.min(A.y,B.y)-12-(i%3)*2;const d=`M ${A.x} ${A.y} L ${A.x} ${y} L ${B.x} ${y} L ${B.x} ${B.y}`;addPath(d,b.phase,'bridge-shadow');addPath(d,b.phase,'bridge-path')});updateStat()}
function updateStat(){let p=document.querySelector('#wiringProgress span');if(p){let base=p.textContent.replace(/ • mostki: \d+/,'');p.textContent=base+` • mostki: ${bridges.length}`}let existing=document.querySelector('.bridge-stat');if(!existing&&consoleBox){existing=document.createElement('span');existing.className='bridge-stat';consoleBox.querySelector('.wiring-console-head')?.appendChild(existing)}if(existing)existing.textContent=`MOSTKI ${bridges.length}`}
function isAdjacent(a,b){const ma=mountedOf(a),mb=mountedOf(b);if(!ma||!mb)return false;const ra=ma.getBoundingClientRect(),rb=mb.getBoundingClientRect();return Math.abs(ra.right-rb.left)<8||Math.abs(rb.right-ra.left)<8}
function click(t){if(!bridgeMode||!eligible(t))return;if(!start){start={id:t.dataset.terminal,el:t,role:t.dataset.role};t.classList.add('bridge-start');return}if(start.id===t.dataset.terminal){clearStart();return}if(!isAdjacent(start.el,t)){flash(t);clearStart();setStatus('Mostek można wykonać tylko między sąsiednimi zabezpieczeniami.');return}if(bridges.some(b=>(b.a===start.id&&b.b===t.dataset.terminal)||(b.b===start.id&&b.a===t.dataset.terminal))){flash(t);clearStart();setStatus('Taki mostek już istnieje.');return}const phase=start.role==='L'? 'L1':start.role;bridges.push({id:'B'+seq++,a:start.id,b:t.dataset.terminal,phase});start.el.classList.remove('bridge-start');start=null;redraw();setStatus(`Dodano mostek ${phase} między sąsiednimi zabezpieczeniami.`)}
function flash(t){t.classList.add('bad-terminal');setTimeout(()=>t.classList.remove('bad-terminal'),500)}
function setStatus(txt){const s=document.getElementById('wiringStatus');if(s)s.innerHTML='<b>MOSTEK:</b> '+txt}
cabinet.addEventListener('click',e=>{if(!bridgeMode)return;const t=e.target.closest('.wire-terminal');if(t&&eligible(t)){e.stopPropagation();e.preventDefault();click(t)}} ,true);
const obs=new MutationObserver(()=>requestAnimationFrame(()=>{document.querySelectorAll('.wire-terminal').forEach(t=>t.classList.toggle('bridge-eligible',bridgeMode&&eligible(t)));redraw()}));obs.observe(cabinet,{childList:true,subtree:true});window.addEventListener('resize',()=>requestAnimationFrame(redraw));
window.ElektrykBridges={getBridges:()=>bridges.slice(),clear:()=>{bridges=[];clearStart();redraw()},redraw};
})();