(()=>{
const PARTS={
 FR:{code:'FR',name:'FR 63A 4P',modules:4,category:'OCHRONA',className:'device-fr wide',top:'L1 • L2 • L3 • N',brand:'ELX MAIN',brandClass:'red',type:'FR',rating:'63A',meta:'4P • 400V',fn:'ROZŁĄCZNIK GŁÓWNY',bottom:'1 • 2 • 3 • N',kind:'fr'},
 RCD:{code:'RCD',name:'RCD 40A / 30mA',modules:2,category:'RCD',className:'device-rcd medium',top:'L • N',brand:'ELX RCD',brandClass:'blue',type:'RCD',rating:'40A',meta:'30mA • Typ A • 2P',fn:'OCHRONA RÓŻNICOWA',bottom:'L • N',kind:'rcd',test:'T'},
 B16:{code:'B16',name:'B16 1P',modules:1,category:'MCB',className:'',top:'1',brand:'ELX MCB',brandClass:'dark',type:'B16',rating:'16A',meta:'1P • 230V',fn:'GNIAZDA',bottom:'2',kind:'mcb'},
 B10:{code:'B10',name:'B10 1P',modules:1,category:'MCB',className:'',top:'1',brand:'ELX MCB',brandClass:'dark',type:'B10',rating:'10A',meta:'1P • 230V',fn:'OŚWIETLENIE',bottom:'2',kind:'mcb'},
 RCBO:{code:'RCBO',name:'RCBO B16 / 30mA',modules:2,category:'RCD',className:'device-rcbo medium',top:'L • N',brand:'ELX RCBO',brandClass:'cyan',type:'RCBO',rating:'B16',meta:'30mA • 1P+N',fn:'MCB + RCD',bottom:'L • N',kind:'rcbo',test:'T',testClass:'yellow'},
 SPD:{code:'SPD',name:'SPD Typ 2',modules:2,category:'OCHRONA',className:'device-spd medium',top:'L • N',brand:'ELX SPD',brandClass:'orange',type:'SPD',rating:'T2',meta:'275V • 1P+N',fn:'PRZEPIĘCIA',bottom:'PE',kind:'spd',spd:true}
};
const TOTAL=18;
let selected=null,occupied=Array(TOTAL).fill(null),mounted=[],seq=1;
const dinZone=document.querySelector('.din-zone'),oldRow=document.querySelector('.devices-row');
if(!dinZone||!oldRow)return;
oldRow.innerHTML='';oldRow.style.display='none';
const grid=document.createElement('div');grid.className='mount-grid';
for(let i=0;i<TOTAL;i++){const s=document.createElement('div');s.className='din-slot';s.dataset.slot=i;s.dataset.label=i+1;grid.appendChild(s)}
dinZone.appendChild(grid);
const hint=document.createElement('div');hint.className='mount-hint';hint.innerHTML='<span><b>MONTAŻ DIN:</b> wybierz aparat w katalogu, potem kliknij wolny moduł.</span><span class="selected-part">Brak wybranego aparatu</span>';dinZone.appendChild(hint);
const activeTask=document.querySelector('.active-task');
if(activeTask){const toolbar=document.createElement('div');toolbar.className='stage2-toolbar';toolbar.innerHTML='<button id="undoMount">↩ COFNIJ APARAT</button><button id="resetMount" class="danger">⟳ WYCZYŚĆ SZYNĘ</button>';activeTask.appendChild(toolbar);const complete=document.createElement('div');complete.className='task-complete';complete.id='taskComplete';complete.textContent='✓ Zadanie montażowe wykonane — wymagane aparaty znajdują się na szynie.';activeTask.appendChild(complete)}
const footerStats=document.querySelectorAll('.workspace-footer b');const moduleStat=footerStats[0]||null,errorStat=footerStats[2]||null;let errors=0;
function usedModules(){return occupied.filter(Boolean).length}
function updateStats(){if(moduleStat){moduleStat.textContent=`${usedModules()} / ${TOTAL}`;moduleStat.className='module-progress '+(usedModules()===TOTAL?'full':usedModules()>13?'warn':'ok')}if(errorStat)errorStat.textContent=errors;updateGoals()}
function setHint(text,state=''){hint.className='mount-hint'+(state?' '+state:'');hint.querySelector('span:first-child').innerHTML=text;setTimeout(()=>{if(state)hint.className='mount-hint'},850)}
function apparatusHtml(p){return `<article class="device ${p.className}" data-kind="${p.kind}"><div class="device-topterm">${p.top}</div><div class="brand-strip ${p.brandClass}">${p.brand}</div><div class="device-type">${p.type}</div><div class="device-rating">${p.rating}</div><div class="device-meta">${p.meta}</div><div class="device-function">${p.fn}</div>${p.test?`<div class="test-btn ${p.testClass||''}">${p.test}</div>`:''}${p.spd?'<div class="spd-window"><span>OK</span></div>':'<div class="lever '+(p.code==='FR'?'redlever':'')+'"><span>I</span><span>O</span></div>'}<div class="device-bottomterm">${p.bottom}</div></article>`}
function canPlace(start,p){if(start<0||start+p.modules>TOTAL)return false;for(let i=start;i<start+p.modules;i++)if(occupied[i])return false;return true}
function clearPreview(){grid.querySelectorAll('.din-slot').forEach(s=>s.classList.remove('preview-ok','preview-bad'))}
function preview(start){clearPreview();if(!selected)return;const p=PARTS[selected],ok=canPlace(start,p);for(let i=start;i<Math.min(TOTAL,start+p.modules);i++)grid.children[i].classList.add(ok?'preview-ok':'preview-bad')}
function mount(start){if(!selected){setHint('<b>MONTAŻ DIN:</b> najpierw wybierz aparat w katalogu.','error');return}const p=PARTS[selected];if(!canPlace(start,p)){errors++;updateStats();setHint(`<b>BŁĄD:</b> ${p.name} potrzebuje ${p.modules} wolnych modułów obok siebie.`,'error');return}const id='M'+seq++;for(let i=start;i<start+p.modules;i++){occupied[i]=id;grid.children[i].classList.add('occupied')}
const wrap=document.createElement('div');wrap.className='mounted-device';wrap.dataset.mountId=id;wrap.dataset.code=p.code;wrap.style.left=`${start/TOTAL*100}%`;wrap.style.width=`${p.modules/TOTAL*100}%`;wrap.innerHTML=`<button class="remove-device" title="Usuń aparat">×</button>${apparatusHtml(p)}`;grid.appendChild(wrap);mounted.push({id,code:p.code,start,modules:p.modules,el:wrap});wrap.querySelector('.remove-device').onclick=e=>{e.stopPropagation();removeMount(id)};wrap.onclick=e=>{e.stopPropagation();grid.querySelectorAll('.mounted-device').forEach(x=>x.classList.remove('selected-mounted'));wrap.classList.add('selected-mounted')};updateStats();setHint(`<b>ZAMONTOWANO:</b> ${p.name} • moduły ${start+1}–${start+p.modules}`,'success')}
function removeMount(id){const m=mounted.find(x=>x.id===id);if(!m)return;for(let i=m.start;i<m.start+m.modules;i++){occupied[i]=null;grid.children[i].classList.remove('occupied')}m.el.remove();mounted=mounted.filter(x=>x.id!==id);updateStats();setHint(`<b>USUNIĘTO:</b> ${m.code} z szyny DIN.`)}
function resetAll(){mounted.slice().forEach(m=>m.el.remove());mounted=[];occupied.fill(null);grid.querySelectorAll('.din-slot').forEach(s=>s.classList.remove('occupied','preview-ok','preview-bad'));errors=0;updateStats();setHint('<b>MONTAŻ DIN:</b> szyna została wyczyszczona.')}
function selectPart(code,card){selected=code;document.querySelectorAll('.catalog-card').forEach(x=>x.classList.remove('install-selected'));card.classList.add('install-selected');hint.querySelector('.selected-part').textContent=`Wybrano: ${PARTS[code].name} • ${PARTS[code].modules}M`;setHint(`<b>GOTOWY DO MONTAŻU:</b> kliknij pierwszy wolny moduł dla ${PARTS[code].name}.`)}
function inferCode(card){const t=(card.querySelector('.mini-device strong')?.textContent||'').trim().toUpperCase();return PARTS[t]?t:null}
document.querySelectorAll('.catalog-card').forEach(card=>{const code=inferCode(card);if(!code)return;card.dataset.part=code;card.dataset.category=PARTS[code].category;card.addEventListener('click',()=>selectPart(code,card))});
grid.addEventListener('mousemove',e=>{const slot=e.target.closest('.din-slot');if(slot)preview(+slot.dataset.slot)});grid.addEventListener('mouseleave',clearPreview);grid.addEventListener('click',e=>{const slot=e.target.closest('.din-slot');if(slot)mount(+slot.dataset.slot)});
const undo=document.getElementById('undoMount'),reset=document.getElementById('resetMount');if(undo)undo.onclick=()=>{const m=mounted[mounted.length-1];if(m)removeMount(m.id)};if(reset)reset.onclick=resetAll;
const categoryButtons=[...document.querySelectorAll('.category-tabs button')];categoryButtons.forEach(btn=>btn.addEventListener('click',()=>{const txt=btn.textContent.trim().toUpperCase();document.querySelectorAll('.catalog-card').forEach(card=>{let show=true;if(txt==='MCB')show=card.dataset.category==='MCB';else if(txt.includes('RCD'))show=card.dataset.category==='RCD';else if(txt==='OCHRONA')show=card.dataset.category==='OCHRONA';card.classList.toggle('hidden-by-filter',!show)})}));
function updateGoals(){const codes=mounted.map(x=>x.code);const checks={FR:codes.includes('FR'),RCD:codes.includes('RCD'),B10:codes.includes('B10'),B16:codes.includes('B16')};document.querySelectorAll('.task-goals span').forEach(span=>{const text=span.textContent.toUpperCase();let key=text.includes('B10')?'B10':text.includes('B16')?'B16':text.includes('RCD')?'RCD':text.includes('FR')?'FR':null;if(!key)return;span.classList.toggle('done',checks[key]);span.classList.toggle('pending',!checks[key]);span.textContent=span.textContent.replace(/^✓\s*|^○\s*/,'')});const done=Object.values(checks).every(Boolean),box=document.getElementById('taskComplete');if(box)box.classList.toggle('show',done);const stars=document.querySelector('.reward em');if(stars)stars.textContent=done?'★★★':'☆☆☆'}
updateStats();
})();